config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

#ゲストログイン
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  scope module: :public do
      root to: 'homes#top'
      get "/about" => "homes#about", as: "about"
      resources :bulletin_boards, only: [:new, :index, :show, :edit, :create, :destroy] do
        resource :favorites, only: [:new,:create, :destroy]
        resources :comments, only: [:create]
      end
      get '/favorited_bulletin_boards', to: 'favorites#index', as: 'favorited_bulletin_boards'
      resources :genres, only: [:index]
      # 論理削除用のルーティング
      patch  '/customers/withdraw' => 'customers#withdraw'
      resources :customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :bulletin_boards, only: [ :index, :show, :destroy]
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_one_attached :image


   has_many :bulletin_boards, dependent: :destroy
   has_many :comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :favorited_bulletin_boards, through: :favorites, source: :bulletin_board
   has_and_belongs_to_many :genres

   validates :nick_name, presence:true

    enum sex: {no＿selection: 0, men: 1, woman: 2,}
    # ゲストログイン
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.nick_name = "ゲスト"
    end
  end
  # is_deletedがfalseならtrueを返す
  def active_for_authentication?
    super && (is_deleted == false)
  end
  # 年齢を計算
  def age
    now = Time.now.utc.to_date
    now.year - birthday.year - ((now.month > birthday.month || (now.month == birthday.month && now.day >= birthday.day)) ? 0 : 1)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    flash[:notice] = "会員情報を変更しました。"
    redirect_to admin_customer_path(@customer)
  end

  private

  def customer_params
    params.require(:customer).permit(:nick_name, :favorite_game, :introduction, :birthday, :sex, :email, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<main class="main-content">
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h2><%= @customer.nick_name %>さんの会員情報編集</h2>
    </div>
  </div>
  <%= form_with model: @customer, url: admin_customer_path, method: :patch, local: true do |f| %>
  <div class="row">
    <div class="col-sm-6 px-sm-0 offset-sm-1">
    <table class="table table-bordered">
       <tr>
         <th class="table-active">会員ID</th>
         <td><%= @customer.id %></td>
       </tr>
    <tr>
      <th class="table-active"><%= f.label "氏名" %></th>
      <td><%= f.text_field :nick_name %></td>
    </tr>


      <tr>
        <th class="table-active"><%= f.label "メールアドレス" %></th>
        <td><%= f.text_field :email %></td>
      </tr>
      <tr>
        <th class="table-active"><%= f.label "会員ステータス" %></th>
        <td><%= f.select :is_deleted, [['有効', false], ['退会済み', true]], {}, { class: 'form-control' } %></td>
      </tr>
    </table>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col-lg-6 px-sm-0 offset-sm-1">
      <%= f.submit '変更を保存' %>
    </div>
  </div>
  <% end %>
</div>
</main>

app/views/admin/customers/index.html.erb
<main class="main-content">
<div class="container">
  <div class="row">
    <h2>会員一覧</h2>

      <table class="table">
        <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to customer.nick_name, admin_customer_path(customer.id) %></td>
            <td><%= customer.email %></td>
           <td class="<%= customer.is_deleted ? 'text-gray' : 'text-green' %>"><%= customer.is_deleted ? '退会済み' : '有効' %></td>
          </tr>
        <% end %>
      </table>
      <%= paginate @customers %>
    </div>
  </div>
</main>

app/views/admin/customers/show.html.erb
<main class="main-content">
<div class='container pt-5'>
    <div class='row'>
        <div class='col-md-6'>
          <h2>マイページ</h2>
            <h5><strong>登録情報</strong>
            </h5>

            <table class='table table-bordered mt-3'>
              <tr>
                <td class='table-active'>ニックネーム</td>
                <td><%= @customer.nick_name %> </td>
              </tr>
              <tr>
                <tr>
                  <td class='table-active'><%= label_tag "年齢" %></td>
                    <td>
                      <% if @customer.birthday.present? %>
                        <%= @customer.age %> 歳
                      <% else %>
                        誕生日を選択してください
                    <% end %>
                    </td>
                </tr>
              <tr>
                <td class='table-active'>好きなゲーム</td>
                <td><%= @customer.favorite_game %> </td>
              </tr>
              <tr>
                <td class='table-active'>好きなゲームジャンル</td>
                <td><%= @customer.genres.pluck(:name).join(', ') %></td>
              </tr>
              <tr>
                <td class='table-active'>自己紹介</td>
                <td><%= @customer.introduction %> </td>
              </tr>
              <tr>
                <td class='table-active'>性別</td>
                <td><%= @customer.sex_i18n %> </td>
              </tr>
            </table>
            <%= link_to "編集する", edit_admin_customer_path(@customer) %>
        </div>
    </div>
</div>
</main>