config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

#ゲストログイン
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  scope module: :public do
      root to: 'homes#top'
      get "/about" => "homes#about", as: "about"
      resources :bulletin_boards, only: [:new, :index, :show, :edit, :create, :destroy] do
        resource :favorites, only: [:new,:create, :destroy]
        resources :comments, only: [:create]
      end
      get '/favorited_bulletin_boards', to: 'favorites#index', as: 'favorited_bulletin_boards'
      resources :genres, only: [:index]
      # 論理削除用のルーティング
      patch  '/customers/withdraw' => 'customers#withdraw'
      resources :customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :bulletin_boards, only: [ :index, :show, :destroy]
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bulletin_board.rb
class BulletinBoard < ApplicationRecord
  belongs_to :customer
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_by, through: :favorites, source: :customer

  validates :title, presence:true
  validates :message, presence:true


  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end
end

app/controllers/admin/bulletin_boards_controller.rb
class Admin::BulletinBoardsController < ApplicationController
  before_action :authenticate_admin!

  def index
     @bulletin_boards = BulletinBoard.all
  end

  def show
    @bulletin_board = BulletinBoard.find(params[:id])
  end


  def destroy
    # byebug
    @bulletin_board = BulletinBoard.find(params[:id])
    @bulletin_board.destroy
    redirect_to admin_bulletin_boards_path
  end

  private

  def bulletin_board_params
    params.require(:bulletin_board).permit(:customer_id, :title, :message,)
  end

end

app/helpers/admin/bulletin_boards_helper.rb
module Admin::BulletinBoardsHelper
end

app/views/admin/bulletin_boards/index.html.erb
<main class="main-content">
  <h1>管理者投稿管理画面</h1>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>ユーザーID</th>
        <th>ニックネーム</th>
        <th>タイトル</th>
        <th>内容</th>
        <th>アクション</th>
      </tr>
    </thead>
    <tbody>
      <% @bulletin_boards.each do |bulletin_board| %>
        <tr>
          <td><%= bulletin_board.customer_id %></td>
          <td><%= link_to bulletin_board.customer.nick_name, admin_customer_path(bulletin_board.customer) %></td>
          <td><%= link_to bulletin_board.title, admin_bulletin_board_path(bulletin_board) %></td>
          <td><%= bulletin_board.message %></td>
          <td><%= link_to "削除", admin_bulletin_board_path(bulletin_board), method: :delete, class: "btn btn-danger btn-sm", data: { confirm: "本当に削除しますか？" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</main>

app/views/admin/bulletin_boards/show.html.erb
<style>
  .custom-border {
    border: 1px inset #000;
  }
</style>

<main class="main-content">
  <div class="container pt-5">
    <div class="row">
      <div class="col text-center">
        <h3>タイトル</h3>
      </div>
    </div>
    <div class="row">
      <div class="col text-center custom-border bg-white">
        <%= @bulletin_board.title %>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col text-center">
        <h3>内容</h3>
      </div>
    </div>
    <div class="row">
      <div class="col text-center custom-border bg-white">
        <%= @bulletin_board.message %>
      </div>
    </div>
    <%= link_to "削除", admin_bulletin_board_path(@bulletin_board), method: :delete, class: "btn btn-danger btn-sm", data: { confirm: "本当に削除しますか？" } %>
    <div class="line-style-comments mt-4">

      <p class="comment-count">コメント件数：<%= @bulletin_board.comments.count %></p>
      <% @bulletin_board.comments.each do |comment| %>
        <div class="comment-line">
          <div class="comment-header">
            <%= link_to admin_customer_path(comment.customer) do %>
              <%= comment.customer.nick_name %>
            <% end %>
            <%= comment.created_at.strftime('%Y/%m/%d') %>
          </div>
          <div class="comment-text">
            <%= comment.comment %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</main>