config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

#ゲストログイン
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  scope module: :public do
      root to: 'homes#top'
      get "/about" => "homes#about", as: "about"
      resources :bulletin_boards, only: [:new, :index, :show, :edit, :create, :destroy] do
        resource :favorites, only: [:new,:create, :destroy]
        resources :comments, only: [:create]
      end
      get '/favorited_bulletin_boards', to: 'favorites#index', as: 'favorited_bulletin_boards'
      resources :genres, only: [:index]
      # 論理削除用のルーティング
      patch  '/customers/withdraw' => 'customers#withdraw'
      resources :customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :bulletin_boards, only: [ :index, :show, :destroy]
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :customers

  validates :name, presence:true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<main class="main-content">
  <h3>ジャンル編集</h3>

  <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
    <div class="row mb-3">
      <div class="col-md-2">
        <%= f.label :name, class: "form-label" %>
      </div>
      <div class="col-md-6">
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="col-md-4">
        <%= f.submit "変更を保存", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</main>

app/views/admin/genres/index.html.erb
<main class="main-content">
  <h3>ジャンル一覧・追加</h3>
  <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
    <div class="row mb-3">
      <div class="col-md-2">
        <%= f.label :name, class: "form-label" %>
      </div>
      <div class="col-md-6">
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="col-md-4">
        <%= f.submit '新規登録', class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>

  <h4>ジャンル一覧</h4>
  <table class="table">
    <thead>
      <tr>
        <th>ジャンル</th>
        <th>アクション</th>
      </tr>
    </thead>
    <tbody>
      <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
          <td>
            <%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success btn-sm" %>
            <%= link_to "削除", admin_genre_path(genre.id), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger btn-sm" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</main>