config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

#ゲストログイン
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  scope module: :public do
      root to: 'homes#top'
      get "/about" => "homes#about", as: "about"
      resources :bulletin_boards, only: [:new, :index, :show, :edit, :create, :destroy] do
        resource :favorites, only: [:new,:create, :destroy]
        resources :comments, only: [:create]
      end
      get '/favorited_bulletin_boards', to: 'favorites#index', as: 'favorited_bulletin_boards'
      resources :genres, only: [:index]
      # 論理削除用のルーティング
      patch  '/customers/withdraw' => 'customers#withdraw'
      resources :customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :bulletin_boards, only: [ :index, :show, :destroy]
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bulletin_board.rb
class BulletinBoard < ApplicationRecord
  belongs_to :customer
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_by, through: :favorites, source: :customer

  validates :title, presence:true
  validates :message, presence:true


  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :bulletin_board

  validates :comment, presence:true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_one_attached :image


   has_many :bulletin_boards, dependent: :destroy
   has_many :comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :favorited_bulletin_boards, through: :favorites, source: :bulletin_board
   has_and_belongs_to_many :genres

   validates :nick_name, presence:true

    enum sex: {no＿selection: 0, men: 1, woman: 2,}
    # ゲストログイン
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.nick_name = "ゲスト"
    end
  end
  # is_deletedがfalseならtrueを返す
  def active_for_authentication?
    super && (is_deleted == false)
  end
  # 年齢を計算
  def age
    now = Time.now.utc.to_date
    now.year - birthday.year - ((now.month > birthday.month || (now.month == birthday.month && now.day >= birthday.day)) ? 0 : 1)
  end

end

app/models/customer_genre.rb
class CustomerGenre < ApplicationRecord
  def change
    create_table :customers_genres, id: false do |t|
      t.belongs_to :customer
      t.belongs_to :genre
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :bulletin_board
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :customers

  validates :name, presence:true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @customers = Customer.page(params[:page]).per(10)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  def reject_end_user
    @end_user = EndUser.find_by(email: params[:end_user][:email])
    if @end_user
      if @end_user.valid_password?(params[:end_user][:password]) && (@end_user.is_deleted == true)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください"
        redirect_to new_end_user_registration_path
      else
        flash[:notice] = "項目を入力してください"
      end
    else
      flash[:notice] = "該当するユーザーが見つかりません"
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_root_path
    else
        root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        admin_session_path
    else
        root_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name, :birthday, :sex, :email, :encrypted_password])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
end

app/helpers/admin/bulletin_boards_helper.rb
module Admin::BulletinBoardsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#808080">
    <div class="container">
      <!-- ナビゲーションヘッダー（タイトルやロゴなど） -->
      <a class="navbar-brand" href="#"></a>

      <!-- メニュー項目 -->
      <ul class="navbar-nav mx-auto">
        <% if admin_signed_in? %>
        <% elsif customer_signed_in? %>
          <li class="nav-item mr-5">
            <%= link_to customer_path(current_customer), class: 'nav-link text-light' do %>
              <i class="fa-solid fa-user"></i> マイページ
            <% end %>
          </li>
          <li class="nav-item mr-5">
            <%= link_to bulletin_boards_path, class: 'nav-link text-light' do %>
              <i class=""></i> 掲示板
            <% end %>
          </li>
          <li class="nav-item mr-5">
            <%= link_to new_bulletin_board_path, class: 'nav-link text-light' do %>
              <i class=""></i> 投稿する
            <% end %>
          </li>
          <li class="nav-item mr-5">
            <%= link_to favorited_bulletin_boards_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-thumbs-up"></i> いいねした投稿
            <% end %>
          </li>
        <% else %>
        <% end %>
      </ul>
    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#808080">
    <div class="container">
      <a class="text-light" href="/"><%= image_tag('logo.png', size: '50x50') %>  ゲーマーコミュニティ</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
              <div class="text-white">管理者としてログイン中です</div>
            <li class="nav-item">
              <%= link_to admin_customers_path, class: 'nav-link text-light' do %>
                <i class=""></i> 会員一覧
              <% end %>
            </li>
            <li class="nav-item">
            <%= link_to admin_bulletin_boards_path, class: 'nav-link text-light' do %>
              <i class=""></i> 掲示板一覧
            <% end %>
          </li>
            <li class="nav-item">
              <%= link_to admin_genres_path, class: 'nav-link text-light' do %>
                <i class=""></i> ジャンル追加・一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class=""></i> ログアウト
              <% end %>
            </li>
          <% elsif customer_signed_in? %>
            <li class="nav-item ">
              <div class="text-white">ログイン中です <%= current_customer.nick_name %></div>
            </li>
            <li class="nav-item">
              <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class=""></i> ログアウト
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to new_customer_registration_path, class: 'nav-link text-light' do %>
                <i class=""></i> 新規登録
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to customer_session_path, class: 'nav-link text-light' do %>
                <i class=""></i> ログイン
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to 'ゲストログイン（閲覧用）', customers_guest_sign_in_path, method: :post, class: 'nav-link text-light' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Games</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/e2e175b78f.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body style="background-color:#DDDDDD">
    <header class="header">
      <%= render 'layouts/header' %>
    </header>
    <main　class="main-content"></main>
    <%= yield %>
    <footer class="footer">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>